### ISSUE TITLE
Создание дополнительного способа перевода денег

### ISSUE THREAD

**Issue by Astromis** [DonkeySmall/TextDetectionDataset#3]
Добрый день. Хотел бы перевести вам на кофе, но возникли проблемы с YouMoney. К сожалению, через него нельзя певести даже небольшую сумму без подтверждения аккаунта паспортом, чего мне делать не хочется.

Не могли бы вы добавить какой-нибудь открытый счет из банка?

**Comment by DonkeySmall** [comment]
Спасибо, не переживайте, лень заморачиваться, это не важно
